# Generated by Django 4.2.23 on 2025-08-14 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_user_created_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="password_reset_required",
            field=models.BooleanField(default=True),
        ),
    ]