# Generated by Django 5.2.4 on 2025-08-14 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_alter_user_managers_remove_user_username_and_more"),
    ]

    operations = []
